// Generated by scripts/build-social-images.mjs. Do not edit by hand.
//
// Articles whose own image is below 600x315 and therefore cannot render a
// wide social card. These fall back to the branded share image so the link
// still previews with something, rather than with nothing.
export const ARTICLES_WITHOUT_A_SOCIAL_IMAGE = new Set<string>([
    "call-for-tender25052018", // 180x300
    "july-2016-board-meeting-key-decisions", // 300x101
    "meeting-with-stax-mdf", // 300x225
    "ncit-hosted-its-first-ever-regional-networking-for-members", // 520x382
    "ncit-starts-women-chapter", // 300x225
    "social-media-for-business", // 300x200
    "vacancy-for-administrative-officer", // 300x225
]);

// Real pixel dimensions of each article image. Declaring width and height on
// og:image means a scraper can lay the card out without downloading the file,
// which is the usual reason a first share renders with no picture.
export const ARTICLE_IMAGE_SIZE: Record<string, { width: number; height: number }> = {
    "a-new-chapter-begins-for-the-northern-ict-industry": { width: 800, height: 332 },
    "action-plan-development-with-wusc": { width: 1024, height: 768 },
    "all-technology-startups-in-sri-lanka-are-requested-to-register-at-startupsl-lk": { width: 1280, height: 960 },
    "application-called-for-employment-based-skill-training-programme-2018": { width: 1024, height: 683 },
    "applications-for-infotel2017-exhibition-from-north-region-it-smes": { width: 1200, height: 900 },
    "awareness-program-on-5g-technology": { width: 1280, height: 960 },
    "boost-your-business-through-ict-event-in-kilinochchi-and-mullaitivu": { width: 1600, height: 1132 },
    "business-digitalization-seminar-in-mannar": { width: 960, height: 540 },
    "call-for-tender25052018": { width: 180, height: 300 },
    "capacity-development-work-shop": { width: 1200, height: 900 },
    "covid19": { width: 626, height: 626 },
    "digital-marketing-challenge-2018": { width: 724, height: 1024 },
    "digital-marketing-challenge-2018-registration-open": { width: 960, height: 720 },
    "digital-roadmap-for-northern-province-online-event-26th-june-2-30pm": { width: 930, height: 1280 },
    "digital-transformation-workshop-batticaloa-2017": { width: 790, height: 528 },
    "first-ever-startup-weekend-mannar-came-to-end": { width: 1024, height: 768 },
    "flood2018": { width: 960, height: 720 },
    "inauguration-meeting-was-held-on-22-feb-2016": { width: 1024, height: 768 },
    "infotel-2017": { width: 1600, height: 1200 },
    "itsmeexhibition": { width: 1024, height: 768 },
    "july-2016-board-meeting-key-decisions": { width: 300, height: 101 },
    "meeting-with-canadian-high-commissioner-mr-david-mckinnon": { width: 1024, height: 768 },
    "meeting-with-cheryl-edison": { width: 1024, height: 578 },
    "meeting-with-deputy-chief-of-mission-robert-b-hilton": { width: 1200, height: 883 },
    "meeting-with-stax-mdf": { width: 300, height: 225 },
    "membership-will-be-open-soon": { width: 1024, height: 768 },
    "ncit-agm-held-and-board-of-directors-elected-for-2018-2019": { width: 1280, height: 960 },
    "ncit-business-incubation-center-declared-open": { width: 1024, height: 683 },
    "ncit-get-together-2016": { width: 806, height: 538 },
    "ncit-got-appreciation-award-from-wusc": { width: 960, height: 720 },
    "ncit-hosted-its-first-ever-regional-networking-for-members": { width: 520, height: 382 },
    "ncit-is-now-trusted-partner-channel-member-of-facebook": { width: 1024, height: 768 },
    "ncit-joined-as-official-challenge-partner-to-succeed-the-climathon-jaffna-2019": { width: 1280, height: 960 },
    "ncit-members-participated-in-indiasoft-2019-hyderabad": { width: 1440, height: 1080 },
    "ncit-starts-women-chapter": { width: 300, height: 225 },
    "ncits-first-ever-tech-talk-in-jaffna": { width: 800, height: 530 },
    "northern-go-digital-2019": { width: 1024, height: 683 },
    "northern-it-sme-business-to-business-expo-2017-organized-in-grant-scale-for-smes-in-northern-province": { width: 1600, height: 1066 },
    "northern-province-ict-education-member-application-form": { width: 1024, height: 458 },
    "presentation-of-itcs-report-on-the-sri-lankan-entrepreneurship-support-ecosystem": { width: 1024, height: 683 },
    "selected-vt-institutions-for-the-employment-based-skill-training-programe-2018": { width: 960, height: 720 },
    "seminar-for-new-ventures": { width: 960, height: 720 },
    "seminar-on-computerization-of-business-in-mannar": { width: 1600, height: 566 },
    "september-board-meeting-key-decisions": { width: 1024, height: 683 },
    "sirakukal-organized-workshop-with-the-support-of-ncit": { width: 1153, height: 1280 },
    "slasscom-presents-sri-lankas-largest-it-bpm-week-2021-ncit-on-board-as-event-partner": { width: 819, height: 1024 },
    "social-media-for-business": { width: 300, height: 200 },
    "startup-weekend-jaffna-2017": { width: 1600, height: 1066 },
    "startup-weekend-jaffna-winning-ideas": { width: 742, height: 384 },
    "startup-weekend-vanni-was-success-full-end-for-startup-weekend-journey-in-2016": { width: 958, height: 718 },
    "startupweekendjaffna": { width: 999, height: 495 },
    "talk-session-kannan": { width: 960, height: 720 },
    "tech-summit-nextwork-2020-scheduled-in-14th-15th-and-16th-february-2020": { width: 1024, height: 768 },
    "the-first-ever-international-tech-summit-nextwork-2020-in-jaffna-successfully-came-to-end": { width: 1600, height: 1098 },
    "the-world-tourism-day-exhibition-2018-was-held-in-jaffna-with-the-theme-of-drive-digital-tourism": { width: 720, height: 960 },
    "vacancy-for-administrative-officer": { width: 300, height: 225 },
    "women-empowerment-and-digitization-workshop": { width: 1024, height: 1024 },
    "world-survey-only-for-startup-companies-age-less-than-10-years-old": { width: 798, height: 542 },
    "youth-entrepreneurship-technical-advisory-forum": { width: 1024, height: 577 },
};
